name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pytest
          python -m pip install flake8 pytest pytest-cov coveralls
          pip install -r requirements.txt
          pip install -r test_requirements.txt
          git clone https://github.com/sibirrer/fastell4py.git
          cd fastell4py
          pip install .
          cd ..
          python -m pip install .
      - name: Test with pytest
        run: |
          cd test
          coverage run --source paltas --omit "**/paltas/Configs/paper_2203_00690/**" -m unittest -v *_tests.py
          coverage lcov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./test/coverage.lcov
